
---
- name: Basic Setup Playbook
  gather_facts: true
  hosts: all
  vars:
    login_user: "{{ ansible_user_id }}"

  roles:
    - role: apt
      when: ansible_facts['os_family'] == 'Debian'

    - role: brew
      when: ansible_facts['os_family'] == 'Darwin'

    - role: yum
      when: ansible_facts['os_family'] == 'RedHat'

    - role: zsh

    - role: dotfiles

