
---
- name: Basic Setup Playbook
  gather_facts: true
  hosts: all
  vars:
    login_user: "{{ ansible_user_id }}"

  tasks:
    - name: "Apt installations"
      include_role:
        name: apt
      when: ansible_facts['os_family'] == 'Debian'

    - name: "Brew installations"
      include_role:
        name: brew
      when: ansible_facts['os_family'] == 'Mac'

    - name: "Yum installation"
      include_role:
        name: yum
      when: ansible_facts['os_family'] == 'RedHat'

    - name: "ZSH setup"
      include_role:
        name: zsh

    - name: "Dotfile setup"
      include_role:
        name: dotfiles

