
---
- name: Basic Setup Playbook
  gather_facts: true
  hosts: all
  vars:
    login_user: "{{ ansible_user_id }}"
  tasks:
    - import_tasks: tasks/debian/packages.yaml
      when: ansible_facts['os_family'] == 'Debian'

    - import_tasks: tasks/mac/brew.yaml
      when: ansible_facts['os_family'] == 'Darwin'

    - import_tasks: tasks/debian/zsh.yaml

    - import_tasks: tasks/dotfiles.yaml
