---
- name: Copy dotfiles to home dir
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "0644"
  with_items:
    - zshrc
    - p10k.zsh
    - gitconfig
  tags:
    - dotfiles


- name: Move custom zsh into place
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
    mode: "0644"
  with_items:
    - aliases.zsh
    - functions.zsh
    - pathappend.zsh
  tags:
    - dotfiles
