---
- name: Copy dotfiles to home dir
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    mode: "0644"
  with_items:
    - zshrc
    - p10k.zsh
    - gitconfig
    - tmux.conf
  tags:
    - dotfiles


- name: Move custom zsh into place
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
    mode: "0644"
  with_items:
    - aliases.zsh
    - functions.zsh
    - pathappend.zsh
  tags:
    - dotfiles


- name: Create .tmux plugins directrory
  file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins"
    state: directory
    mode: "0774"
  tags:
  - dotfiles


- name: Clone TPM
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    accept_hostkey: yes
    update: no
    force: no
    version: 693e5a2
  tags:
  - dotfiles


