---
- name: Copy .zshrc
  copy:
    src: "zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  tags:
    - dotfiles

- name: Copy .p10k.zsh
  copy:
    src: "p10k.zsh"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
  tags:
    - dotfiles

- name: Copy gitconfig
  copy:
    src: "gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  tags:
    - dotfiles
