---
- name: Copy .zshrc
  copy:
    src: "zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  tags:
    - dotfiles

- name: Copy .p10k.zsh
  copy:
    src: "p10k.zsh"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
  tags:
    - dotfiles

- name: Copy gitconfig
  copy:
    src: "gitconfig"
    dest: "{{ ansible_env.HOME }}/.gitconfig"
  tags:
    - dotfiles

- name: Move custom zsh into place
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
  with_items:
    - aliases.zsh
    - functions.zsh
  tags:
    - dotfiles
