---
- name: Include APT package list
  include_vars: vars/apt.yaml
  become: true
  tags:
    - apt
    - debian

# - name: Include snap package list
#   include_vars: vars/snap.yaml
#   become: true
#   tags:
#     - snap
#     - debian

- name: Update/Upgrade apt
  become: true
  apt:
    update_cache: true
    upgrade: dist
  tags:
    - apt
    - debian

- name: Manage apt packages
  become: true
  apt:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('latest') }}"
  with_dict: "{{apt}}"
  tags:
    - apt
    - debian

# - name: Manage snap packages
#   become: true
#   community.general.snap:
#     name: "{{ item.key }}"
#     state: "{{ item.value.state | default('present') }}"
#     classic: true
#   with_dict: "{{snap}}"
#   tags:
#     - snap
#     - debian

- name: Check AWS CLI is installed
  stat:
    path: /usr/local/aws-cli/
  register: aws_cli_installed
  tags:
    - aws_cli

- name: Install AWS CLI
  block:
    - name: Unzip AWS CLI
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: ~/
        remote_src: yes

    - name: Install AWS CLI
      shell:
        cmd: "sudo ./install"
        # become: true
        chdir: ~/aws
        creates: /usr/local/aws-cli/

    - name: Cleanup AWS install
      file:
        path: ~/aws
        state: absent

  when: not aws_cli_installed.stat.exists
  tags:
    - aws_cli